spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: ##jdbc:mysql://192.168.4.236:3306/meidui_settlement?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: ##root
    password: ##meidui@2016.?!
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      connection-init-sql: SELECT 1
      connection-test-query: SELECT 1 FROM DUAL
      auto-commit: true
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      maximum-pool-size: 300
      minimumIdle : 10
      pool-name: harika-cp
      
eureka:
  client:
    serviceUrl:
      defaultZone: http://10.116.21.93:9001/eureka/
    registry-fetch-interval-seconds: 10  
    healthcheck:
      enabled: true  
  instance:
    hostname: 10.116.21.93
    lease-renewal-interval-in-seconds: 15      # 心跳时间，即服务续约间隔时间（缺省为30s）
    lease-expiration-duration-in-seconds: 30  # 发呆时间，即服务续约到期时间（缺省为90s）   

## it doesn't work configuring here so change to configure it in MyBatisConfig.java.  
#mybatis:
#  mapper-locations: classpath*:com/meiduimall/settlement/mapper/*Mapper.xml
#  type-aliases-package: com.meiduimall.settlement.model

# redis
config:
  jedis: 
    jedisShardInfo:  
      host: ##192.168.4.236
      port: ##6379  
      password: ##meiduiredis2016
      database: 1
    maxTotal: 1024  
    maxIdle: 250  
    maxWaitMillis: 2000 
    testOnBorrow: true
    testOnReturn: true
hystrix:  
  command:  
    default:  
      execution:  
        isolation:  
          thread:  
            timeoutInMilliseconds: 3000 #缺省为1000
            
            
#自定义的属性和值  
myProps :
  oauthSignatureMethod : MD5
  oauthVersion : 1.0
  oauthAccessorSecret : 25164dbe226e1d26c109b64c7e6d14e8
  oauthConsumerKey : 7aee283f0dd2a877d8cb2f7464b3a9da
  #http://vipt.meiduimall.com/
  url : http://10.170.13.129:18123/
  belong : Authorized/querySecondLevelShareMem
  apiUpdFirstReferrerCash : AuthorizationAccount/accountBalanceChanges
  ##callback url from o2o
  o2oUrl : http://10.24.167.124/
  o2oSaveOrderBillStatu : op/index.php/java/saveOrderBillStatus
  o2oAddProxyFee : op/index.php/java/addProxyFee
  o2oApiKey : mdo2okey
  ##msg channel
  ##url from sms
  smsUrl : http://10.116.21.93:20000/
  smsSendMessage : notify/short_msg_service/v1/send_common_sms_message
  ##phones:xuyanxiong,guidonglin
  smsPhones : 13410336992,13798431927,18898447755